[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    "lib/openzeppelin-contracts-upgradeable/contracts/=node_modules/@openzeppelin/contracts-upgradeable/",
    "extension/=node_modules/@thirdweb-dev/contracts/extension/",
    "interface/=node_modules/@thirdweb-dev/contracts/prebuilts/interface/",
    "infra/=node_modules/@thirdweb-dev/contracts/infra/",
    "external-deps/=node_modules/@thirdweb-dev/contracts/external-deps/",
    "lib/=node_modules/@thirdweb-dev/contracts/lib/",
    "eip/=node_modules/@thirdweb-dev/contracts/eip/"
]
optimizer = true
optimizer_runs = 1  # Optimize for contract size (deployment) over gas costs (execution)
via_ir = true
solc_version = "0.8.20"
evm_version = "paris"

[profile.test]
fuzz_runs = 10000
invariant_runs = 1000

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

